-- 1. Открой Supabase -> SQL Editor -> New query
-- 2. Вставь этот SQL целиком и нажми Run.
--
-- Эта схема подходит для ПЕРВОГО ПРОТОТИПА.
-- Она не реализует полноценную модерацию/антиспам/защиту публичного сервиса.

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 24),
  text text not null check (char_length(text) between 1 and 1000),
  created_at timestamptz not null default now()
);

alter table public.messages enable row level security;

-- Для тестового прототипа разрешаем читать и добавлять сообщения без аккаунта.
create policy "public can read messages"
on public.messages
for select
to anon
using (true);

create policy "public can insert messages"
on public.messages
for insert
to anon
with check (
  char_length(name) between 1 and 24
  and char_length(text) between 1 and 1000
);

-- Realtime
alter publication supabase_realtime add table public.messages;
